# Copyright (c) TRAI
# SPDX-License-Identifier: MIT

name: Copywrite Check
on: [push, pull_request]

jobs:
  copywrite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install copywrite
        uses: hashicorp/setup-copywrite@v1.1.3

      - name: Validate Header Compliance
        run: copywrite headers --plan

      - name: Validate License File
        run: copywrite license --plan
